### ISSUE TITLE
ソースコードで「=」の前後にコメント「//」があると正しく動作しません。

### ISSUE THREAD

**Issue by KokiOkai** [amanhirohisa/JavaVariableExtractor#1]
## 概要
ソースコードで「=」の前後にコメント「//」があると正しく動作しません。

## 失敗例
1. プロジェクトfastjsonの[ファイル例①](https://github.com/alibaba/fastjson/blob/master/src/test/java/com/alibaba/json/bvt/bug/Bug_for_issue_283.java)で、コード18行目の変数の構文情報が正しく取得できない。
2. プロジェクトelasticsearchの[ファイル例②](https://github.com/elastic/elasticsearch/blob/main/server/src/test/java/org/elasticsearch/transport/RemoteClusterServiceTests.java)で、コード458行目、461行目の変数の構文情報が正しく取得できない。

## 失敗時の出力（ファイル例①）
![バグ例](https://user-images.githubusercontent.com/105481222/232709736-9e38cf8b-998b-44ae-aaaf-f4faf2976976.jpg)

**Comment by amanhirohisa** [comment]
詳細なバグ報告をありがとうございました．
変数名と型名を文字列として抽出する際に，通常ならば問題ないのですが，初期化式に "//" が入っていると toString() による文字列化の際に名前と型名にそれぞれ "//" と改行が入り込んでしまう不具合があったようです．
該当する部分のメソッドを変更することで解決できたと考えています．
改訂版を 4.0.1 として公開いたしました．
