### ISSUE TITLE
ソースコードで単行に「/*  */」「/**  */」があると正しく動作しません。

### ISSUE THREAD

**Issue by KokiOkai** [amanhirohisa/JavaVariableExtractor#2]
## 概要
ソースコードで単行に「/*  \*/」「/**  */」があると正しく動作しません。

## 失敗例
1. プロジェクトfastjsonの[ファイル例①](https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/parser/ParserConfig.java)で、コード1185行目の変数の構文情報が正しく取得できない。
2. プロジェクトelasticsearchの[ファイル例②](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/plugins/scanners/StablePluginsRegistry.java)で、コード41行目の変数の構文情報が正しく取得できない。
ただし、コード33行目については正しく取得できている。

## 失敗時の出力（ファイル例①）
![バグ1](https://user-images.githubusercontent.com/105481222/236397356-4bea2ec8-d3a4-4416-a05b-dd997ec3f3e4.jpg)

## 失敗時の出力（ファイル例②）
緑の枠で囲まれた箇所は、対象コード33行目に「/*  */」が含まれていますが、正しく動作しました。<br>
![バグ2](https://user-images.githubusercontent.com/105481222/236404262-26f863da-5924-488f-a7b5-e161ec1b373b.jpg)

**Comment by amanhirohisa** [comment]
ご報告を誠にありがとうございました．たびたび申し訳ありません... 

昨日修正した #1 と同様の不具合がメソッドの引数について残ってしまっておりました．
修正版を v4.0.2 としてリリースいたしました．
